name = "backend"
main = "src/index.ts"
compatibility_date = "2025-01-13"

# compatibility_flags = [ "nodejs_compat" ]

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiMGE2OTExMDQtYTdjYy00MjViLWIxZGMtMGY1OTE0OTI3ZTY0IiwidGVuYW50X2lkIjoiNDBlZjhjM2U5MDZmN2IxODg1ZDkwNmFkNjFkMGE3MTU4NDdjZWFhMGIxOWU5ZmE4MWE1YTVkMTNjOTQ4ZTk2YiIsImludGVybmFsX3NlY3JldCI6IjJlYjMxMWM2LWE1M2QtNDJmNi1hYzhlLTA1MzQwODYxYjMxMCJ9.GPRi24ZIQAt3EShyXB8x8iEU3NNJ97I0uTpA14y-BiI"
JWT_SECRET = "errihook"
# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"

# [observability]
# enabled = true
# head_sampling_rate = 1